import type { PageFrictionKind, PageFrictionReport } from './types.js';
/**
 * Universal page friction probe — runs on any page after navigation/read.
 * Site-agnostic; complements network 429 and policy HITL (system_captcha_wait).
 */
export declare const PAGE_FRICTION_JS = "(() => {\n  const title = (document.title || '').toLowerCase()\n  const path = (location.pathname || '').toLowerCase()\n  const text = (document.body?.innerText || '').slice(0, 5000).toLowerCase()\n  const blob = title + ' ' + path + ' ' + text\n\n  const kinds = []\n  const hasPassword = Boolean(document.querySelector('input[type=password]'))\n  const loginish = /login|sign[\\s-]?in|register|sign[\\s-]?up|auth|\u767B\u5F55|\u6CE8\u518C|\u5E10\u53F7|\u8D26\u53F7/.test(blob)\n  if (hasPassword && loginish) kinds.push('login')\n\n  const captchaDom = Boolean(\n    document.querySelector(\n      '[class*=\"captcha\"],[id*=\"captcha\"],iframe[src*=\"captcha\"],[class*=\"geetest\"],[class*=\"turnstile\"],#challenge-form,[data-sitekey]'\n    )\n  )\n  const captchaText = /captcha|\u9A8C\u8BC1\u7801|\u4EBA\u673A|verify you are human|security check|\u6ED1\u52A8\u9A8C\u8BC1|\u70B9\u9009|unusual traffic|are you a robot/.test(\n    blob\n  )\n  if (captchaDom || captchaText) kinds.push('captcha')\n  if (/verify you are human|checking your browser|just a moment|\u8BF7\u5B8C\u6210\u9A8C\u8BC1|\u5B89\u5168\u9A8C\u8BC1/.test(blob)) {\n    kinds.push('human_verify')\n  }\n\n  if (/too many requests|rate limit|429|\u8BBF\u95EE\u8FC7\u4E8E\u9891\u7E41|\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41|try again later|\u7A0D\u540E\u518D\u8BD5|slow down/.test(blob)) {\n    kinds.push('rate_limit')\n  }\n  if (/not available in your country|\u5730\u533A\u9650\u5236|region|geo.?block|\u6B64\u5185\u5BB9\u4E0D\u53EF|unavailable in your/.test(blob)) {\n    kinds.push('geo_block')\n  }\n  if (/access denied|forbidden|403|\u62D2\u7EDD\u8BBF\u95EE|\u65E0\u6743\u8BBF\u95EE/.test(blob)) kinds.push('access_denied')\n\n  const cookieBanner = Boolean(\n    document.querySelector(\n      '#onetrust,[class*=\"cookie\"],[id*=\"cookie-banner\"],[aria-label*=\"cookie\"],[class*=\"consent-banner\"]'\n    )\n  )\n  if (cookieBanner) kinds.push('cookie_banner')\n\n  const paywallMarketing = /subscribe to (watch|read)|\u4F1A\u5458\u4E13\u4EAB|\u4ED8\u8D39|vip only|\u5F00\u901Avip|vip\u4E13\u4EAB|\u6700\u4F4E\u4EC5\u9700|\u65B0\u5BA2\u4F4E\u81F3/.test(blob)\n  const paywallHard = /\u767B\u5F55\u540E\u89C2\u770B|\u8BF7\u767B\u5F55\u540E|sign in to view|unlock this|login to download|\u8BF7\u5148\u767B\u5F55/.test(blob)\n  if (paywallMarketing || paywallHard) kinds.push('paywall')\n\n  const hasDownloadCta = /\u5355\u7BC7\u4E0B\u8F7D|\u6279\u91CF\u4E0B\u8F7D|\u7ACB\u5373\u4E0B\u8F7D|\\bdownload\\b/.test(blob)\n  const blockingKinds = kinds.filter((k) => {\n    if (k === 'cookie_banner') return false\n    if (k === 'paywall') {\n      if (paywallHard || (hasPassword && loginish)) return true\n      if (hasDownloadCta && !hasPassword) return false\n      return paywallHard\n    }\n    return true\n  })\n  return {\n    url: location.href,\n    title: document.title || '',\n    kinds,\n    blocking: blockingKinds.length > 0,\n    cookieBanner,\n  }\n})()";
export declare function parsePageFrictionPayload(raw: unknown): PageFrictionReport | null;
/** Text-only fallback when executeJs unavailable (dom_read body). */
export declare function classifyTextFriction(text: string): PageFrictionKind[];
/** Marketing VIP copy on an otherwise usable page should not block automation. */
export declare function isHardPaywall(report: PageFrictionReport): boolean;
