import type { StudioAnnotation } from './editor/draw-kit/annotation-types.js'
import {
  DEFAULT_BLUR_RADIUS,
  DEFAULT_FONT_SIZE,
  DEFAULT_HIGHLIGHTER_STROKE,
  DEFAULT_MOSAIC_BLOCK,
  DEFAULT_STICKER_EMOJI,
  DEFAULT_STICKER_SIZE,
  DEFAULT_STROKE,
  STUDIO_BLUR_MAX,
  STUDIO_BLUR_MIN,
  STUDIO_FONT_MAX,
  STUDIO_FONT_MIN,
  STUDIO_HIGHLIGHTER_MAX,
  STUDIO_HIGHLIGHTER_MIN,
  STUDIO_MOSAIC_MAX,
  STUDIO_MOSAIC_MIN,
  STUDIO_STICKER_MAX,
  STUDIO_STICKER_MIN,
  STUDIO_STROKE_MAX,
  STUDIO_STROKE_MIN,
  STUDIO_BLUR_RADIUS,
  STUDIO_COLORS,
  STUDIO_FONT_SIZES,
  STUDIO_HIGHLIGHTER_STROKES,
  STUDIO_MOSAIC_BLOCKS,
  STUDIO_STICKERS,
  STUDIO_STICKER_SIZES,
  STUDIO_STROKES,
} from './editor/draw-kit/presets.js'

export type ScreenshotStudioSession = {
  id: string
  createdAt: number
  baseImageDataUrl: string
  sourceTabId?: number
  sourceWindowId?: number
  sourceUrl?: string
  annotations: StudioAnnotation[]
}

export type { StudioAnnotation, StudioTool } from './editor/draw-kit/annotation-types.js'

export {
  STUDIO_COLORS,
  STUDIO_STROKES,
  STUDIO_STROKE_MIN,
  STUDIO_STROKE_MAX,
  STUDIO_HIGHLIGHTER_STROKES,
  STUDIO_HIGHLIGHTER_MIN,
  STUDIO_HIGHLIGHTER_MAX,
  STUDIO_FONT_SIZES,
  STUDIO_FONT_MIN,
  STUDIO_FONT_MAX,
  STUDIO_MOSAIC_BLOCKS,
  STUDIO_MOSAIC_MIN,
  STUDIO_MOSAIC_MAX,
  STUDIO_BLUR_RADIUS,
  STUDIO_BLUR_MIN,
  STUDIO_BLUR_MAX,
  STUDIO_STICKER_SIZES,
  STUDIO_STICKER_MIN,
  STUDIO_STICKER_MAX,
  STUDIO_STICKERS,
  DEFAULT_STROKE,
  DEFAULT_HIGHLIGHTER_STROKE,
  DEFAULT_FONT_SIZE,
  DEFAULT_MOSAIC_BLOCK,
  DEFAULT_BLUR_RADIUS,
  DEFAULT_STICKER_SIZE,
  DEFAULT_STICKER_EMOJI,
}
