#!/usr/bin/env bash
# Propagate LLM secrets from a single file to Hermes, OpenInspector, Open Notebook.
#
# Usage:
#   ./sync-content-studio-secrets.sh           # sync from $HERMES_HOME/secrets.env
#   ./sync-content-studio-secrets.sh --init      # create secrets.env from current .env
#   ./sync-content-studio-secrets.sh --notebook  # also PATCH Open Notebook DB credentials via API
#
# See hermes-dev/config/secrets.env.example

if [ -z "${BASH_VERSION:-}" ]; then
  exec /usr/bin/env bash "$0" "$@"
fi

set -euo pipefail

OPS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd "$OPS_SCRIPT_DIR/../.." && pwd)"
# shellcheck source=/dev/null
source "$BUNDLE_ROOT/env.sh"
# shellcheck source=/dev/null
source "$BUNDLE_ROOT/stack/ports.env" 2>/dev/null || true

SECRETS_FILE="${CONTENT_STUDIO_SECRETS:-$HERMES_HOME/secrets.env}"
PROXY_PORT="${OPENINSPECTOR_PROXY_PORT:-8080}"
NOTEBOOK_API_PORT="${NOTEBOOK_API_PORT:-5055}"

DO_INIT=0
DO_NOTEBOOK=0
QUIET=0
for arg in "$@"; do
  case "$arg" in
    --init) DO_INIT=1 ;;
    --notebook) DO_NOTEBOOK=1 ;;
    --quiet) QUIET=1 ;;
  esac
done

log() { [[ "$QUIET" == "1" ]] || echo "[secrets-sync] $*"; }
warn() { echo "[secrets-sync] WARN: $*" >&2; }

set_env_key() {
  local file="$1" key="$2" value="$3"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  local tmp
  tmp="$(mktemp)"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    awk -v k="$key" -v v="$value" '
      BEGIN { found=0 }
      $0 ~ "^" k "=" { print k "=" v; found=1; next }
      { print }
      END { if (!found) print k "=" v }
    ' "$file" >"$tmp"
  else
    cp "$file" "$tmp"
    printf '%s=%s\n' "$key" "$value" >>"$tmp"
  fi
  mv "$tmp" "$file"
}

strip_v1_suffix() {
  local url="$1"
  url="${url%/}"
  url="${url%/v1}"
  echo "$url"
}

init_secrets_from_profile() {
  local hermes_env="$HERMES_HOME/.env"
  local nb_env="$OPEN_NOTEBOOK_DIR/.env"
  local oi_env="$OPENINSPECTOR_DIR/.env"
  local key="" upstream="" proxy="http://127.0.0.1:${PROXY_PORT}/v1"

  if [[ -f "$hermes_env" ]]; then
    # shellcheck disable=SC1090
    source "$hermes_env" 2>/dev/null || true
    key="${CUSTOM_API_KEY:-${OPENROUTER_API_KEY:-}}"
  fi
  if [[ -f "$nb_env" ]]; then
    # shellcheck disable=SC1090
    source "$nb_env" 2>/dev/null || true
    key="${key:-${OPENAI_COMPATIBLE_API_KEY:-}}"
    if [[ -n "${OPENAI_COMPATIBLE_BASE_URL:-}" ]]; then
      upstream="$(strip_v1_suffix "$OPENAI_COMPATIBLE_BASE_URL")"
    fi
  fi
  if [[ -f "$oi_env" ]]; then
    # shellcheck disable=SC1090
    source "$oi_env" 2>/dev/null || true
    upstream="${upstream:-${BASE_URL:-}}"
  fi
  upstream="${upstream:-https://newapi.yuaiweiwu.com}"

  cat >"$SECRETS_FILE" <<EOF
# Auto-generated by sync-content-studio-secrets.sh --init
LLM_UPSTREAM_BASE_URL=${upstream}
LLM_API_KEY=${key:-sk-your-key-here}
LLM_PROXY_URL=${proxy}
EOF
  log "Created $SECRETS_FILE — edit LLM_API_KEY if needed, then re-run without --init"
}

if [[ "$DO_INIT" == "1" ]]; then
  if [[ -f "$SECRETS_FILE" ]]; then
    warn "$SECRETS_FILE already exists; not overwriting (remove it first to re-init)"
    exit 1
  fi
  init_secrets_from_profile
  DO_NOTEBOOK=1
fi

if [[ ! -f "$SECRETS_FILE" ]]; then
  warn "Missing $SECRETS_FILE"
  echo "  cp $ROOT_DIR/config/secrets.env.example $SECRETS_FILE" >&2
  echo "  # or: $0 --init" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$SECRETS_FILE"
set +a

: "${LLM_API_KEY:?LLM_API_KEY must be set in $SECRETS_FILE}"
: "${LLM_UPSTREAM_BASE_URL:?LLM_UPSTREAM_BASE_URL must be set in $SECRETS_FILE}"

LLM_PROXY_URL="${LLM_PROXY_URL:-http://127.0.0.1:${PROXY_PORT}/v1}"
UPSTREAM_NO_V1="$(strip_v1_suffix "$LLM_UPSTREAM_BASE_URL")"

# ── Hermes profile .env ───────────────────────────────────────────────────
hermes_env="$HERMES_HOME/.env"
set_env_key "$hermes_env" CUSTOM_API_KEY "$LLM_API_KEY"
set_env_key "$hermes_env" OPENROUTER_API_KEY "$LLM_API_KEY"
log "Updated $hermes_env (CUSTOM_API_KEY, OPENROUTER_API_KEY)"

# ── Open Notebook .env（走本地 Proxy，不直连上游）────────────────────────────
nb_env="$OPEN_NOTEBOOK_DIR/.env"
if [[ -f "$nb_env" ]]; then
  set_env_key "$nb_env" OPENAI_COMPATIBLE_API_KEY "$LLM_API_KEY"
  set_env_key "$nb_env" OPENAI_COMPATIBLE_BASE_URL "$LLM_PROXY_URL"
  set_env_key "$nb_env" OPENROUTER_API_KEY "$LLM_API_KEY"
  log "Updated $nb_env → base_url=$LLM_PROXY_URL"
fi

# ── OpenInspector .env（只配上游 BASE_URL，key 由客户端 Authorization 透传）──
oi_env="$OPENINSPECTOR_DIR/.env"
if [[ -d "$OPENINSPECTOR_DIR" ]]; then
  touch "$oi_env"
  set_env_key "$oi_env" BASE_URL "$UPSTREAM_NO_V1"
  log "Updated $oi_env BASE_URL=$UPSTREAM_NO_V1"
fi

# ── MoneyPrinterTurbo config.toml（脚本生成视频用的 LLM）────────────────────
mpt_cfg="$MONEYPRINTER_DIR/config.toml"
mpt_sync="$ROOT_DIR/scripts/sync-mpt-llm-config.py"
if [[ -f "$mpt_cfg" && -f "$mpt_sync" ]]; then
  DEEPAGENTS_PYTHON="${DEEPAGENTS_PYTHON:-python3}"
  if [[ -f "$ROOT_DIR/../scripts/deepagents-python.env.sh" ]]; then
    # shellcheck source=/dev/null
    source "$ROOT_DIR/../scripts/deepagents-python.env.sh"
    DEEPAGENTS_PYTHON="${DEEPAGENTS_PYTHON:-python3}"
  fi
  "$DEEPAGENTS_PYTHON" "$mpt_sync" \
    --config "$mpt_cfg" \
    --api-key "$LLM_API_KEY" \
    --base-url "$LLM_PROXY_URL" \
    && log "Updated MPT $mpt_cfg → openai_base_url=$LLM_PROXY_URL" \
    || warn "MPT config sync failed (is toml installed?)"
fi

# ── Hermes config.yaml：确保 base_url 指向 Proxy（若存在 yq）────────────────
config_yaml="$HERMES_HOME/config.yaml"
if [[ -f "$config_yaml" ]] && command -v yq >/dev/null 2>&1; then
  yq -i ".model.base_url = \"${LLM_PROXY_URL}\"" "$config_yaml" 2>/dev/null || true
  yq -i '.providers.manifest.base_url = "'"${LLM_PROXY_URL}"'"' "$config_yaml" 2>/dev/null || true
  log "Updated $config_yaml model.base_url via yq"
elif [[ -f "$config_yaml" ]]; then
  log "Tip: install yq to auto-update config.yaml base_url, or set model.base_url=$LLM_PROXY_URL manually"
fi

# ── Open Notebook DB credentials（可选）────────────────────────────────────
if [[ "$DO_NOTEBOOK" == "1" ]]; then
  nb_api="http://127.0.0.1:${NOTEBOOK_API_PORT}"
  if curl -fsS "${nb_api}/docs" >/dev/null 2>&1; then
    sync_py="$ROOT_DIR/scripts/sync-notebook-llm-credentials.py"
    if [[ -f "$sync_py" ]]; then
      DEEPAGENTS_PYTHON="${DEEPAGENTS_PYTHON:-}"
      if [[ -z "$DEEPAGENTS_PYTHON" && -f "$ROOT_DIR/../scripts/deepagents-python.env.sh" ]]; then
        # shellcheck source=/dev/null
        source "$ROOT_DIR/../scripts/deepagents-python.env.sh"
      fi
      py="${DEEPAGENTS_PYTHON:-python3}"
      "$py" "$sync_py" \
        --api-url "$nb_api" \
        --api-key "$LLM_API_KEY" \
        --base-url "$LLM_PROXY_URL" \
        && log "Patched Open Notebook credentials via API" \
        || warn "notebook credential sync failed"
    fi
  else
    warn "Open Notebook API not up; skip --notebook (start stack first or run sync again later)"
  fi
fi

log "Done. LLM key/upstream: edit only $SECRETS_FILE then re-run this script."
log "TTS keys: edit $HERMES_HOME/config/tts-providers.yaml (not synced here)."
